Revert "Make -pyc packages mandatory"
Making -pyc mandatory creates problems for building python3 itself,
which has pyc0 pyc1 and what-not.

>>> ERROR: python3-tests*: Found __pycache__ but package name doesn't end with -pyc

Revert for now.

This reverts commit e092af60c4f49a5d218b9a109bcfda5146c9a555.